"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import RadialNav from "@/components/kerb/RadialNav";
import { getIncidents, type IncidentListItem } from "@/lib/api/incidents";

export default function IncidentsPage() {
  const [items, setItems] = useState<IncidentListItem[]>([]); const [state, setState] = useState(""); const [status, setStatus] = useState("loading"); const [error, setError] = useState("");
  useEffect(() => { getIncidents(state ? { state } : {}).then((result) => { setItems(result.items); setStatus("ready"); }).catch((cause) => { setError(cause instanceof Error ? cause.message : "Unable to load incidents"); setStatus("error"); }); }, [state]);
  return <main className="min-h-screen bg-[hsl(var(--kerb-bg))] text-kerb-white"><RadialNav active="incidents" /><div className="mx-auto max-w-[1400px] px-5 pt-28 pb-20 sm:px-8 lg:px-12"><header className="border-b border-white/10 pb-9"><p className="font-mono text-[10px] tracking-[0.25em] text-kerb-red uppercase">KERB / STEWARD QUEUE</p><h1 className="mt-4 font-display text-6xl font-bold uppercase sm:text-8xl">Incidents</h1><p className="mt-5 text-base text-kerb-white/60">Prioritized evidence requiring steward attention.</p></header><div className="mt-8 flex flex-wrap gap-2">{["", "VIOLATION_CANDIDATE", "UNCERTAIN", "NO_VIOLATION"].map((value) => <button key={value || "ALL"} type="button" onClick={() => setState(value)} className={`border px-3 py-2 font-mono text-[9px] tracking-[0.14em] uppercase ${state === value ? "border-kerb-red text-kerb-red" : "border-white/15 text-kerb-white/45"}`}>{value ? value.replaceAll("_", " ") : "ALL"}</button>)}</div><section className="mt-8 border border-white/10">{status === "loading" && <StateMessage text="Loading incident queue..." />}{status === "error" && <StateMessage text={error} />}{status === "ready" && !items.length && <StateMessage text="No incidents found for this filter." />}{items.map((incident) => <Link href={`/incidents/${incident.incident_id}`} key={incident.incident_id} className="flex flex-wrap items-center justify-between gap-5 border-b border-white/10 p-5 transition hover:bg-white/[0.03] last:border-0"><div><p className="font-mono text-[10px] tracking-[0.18em] text-kerb-red">{incident.incident_id} · TRACK {incident.track_id}</p><p className="mt-2 font-display text-2xl uppercase">{incident.state.replaceAll("_", " ")}</p><p className="mt-1 font-mono text-[10px] text-kerb-white/40">{incident.timestamp_s.toFixed(2)}s · FRAME {incident.frame_index}</p></div><div className="text-right"><p className="font-display text-3xl">{incident.trust_score}</p><p className="font-mono text-[9px] tracking-[0.14em] text-kerb-white/40 uppercase">TRUST · {incident.review_status.replaceAll("_", " ")}</p></div></Link>)}</section></div></main>;
}

function StateMessage({ text }: { text: string }) { return <div className="px-6 py-16 text-center font-mono text-xs text-kerb-white/45">{text}</div>; }
